import {test,expect} from '@playwright/test';
test('actual authorized workbench retains the original sample chart variants and responsive interactions',async({page})=>{
  await page.goto('/dashboard');await expect(page.getByRole('button',{name:'图表演示',exact:true})).toHaveCount(0);await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('admin123');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('group',{name:'工作台视图'})).toBeVisible();
  await page.getByRole('button',{name:'图表演示',exact:true}).click();await expect(page.locator('.dashboard-demo-chart svg')).toHaveCount(4);await expect(page.getByText('演示数据用于展示图表交互，不代表当前企业的实际业务统计。')).toBeVisible();
  await page.getByRole('button',{name:/^消息：/}).focus();await page.keyboard.press('Space');await page.getByText('查看消息趋势数据',{exact:true}).click();await expect(page.getByRole('table',{name:'消息趋势演示数据'}).getByRole('row')).toHaveCount(8);await expect(page.getByRole('table',{name:'消息趋势演示数据'}).getByRole('row').nth(1)).toHaveText('Mon200180');
  await page.getByText('查看文章分布数据',{exact:true}).click();await expect(page.getByRole('table',{name:'文章分布演示数据'}).getByRole('row').nth(5)).toHaveText('Forecasts59');const legend=page.getByRole('group',{name:'预算比较图例'}).getByRole('button',{name:'Actual Spending',exact:true});await legend.focus();await page.keyboard.press('Space');await expect(legend).toHaveAttribute('aria-pressed','false');await page.keyboard.press('Space');await expect(legend).toHaveAttribute('aria-pressed','true');
  await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);for(const chart of await page.locator('.dashboard-demo-chart svg').all()){expect((await chart.boundingBox())?.width).toBeGreaterThan(100);}
  await page.getByRole('button',{name:'工作台',exact:true}).click();await expect(page.getByRole('heading',{name:'你的工作空间已就绪'})).toBeVisible();await expect(page.locator('.dashboard-demo-chart')).toHaveCount(0);await page.getByRole('button',{name:'图表演示',exact:true}).click();await expect(page.locator('.dashboard-demo-chart svg')).toHaveCount(4);
});
