import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {inflateRawSync} from 'node:zlib';
import type {PreviewResponse,TableDetail} from '../../generated/api';
const owned=process.env.EFORGE_E2E_GENERATOR_TABLE;
if(!owned||!/^gmanager_[a-f0-9]{12}$/.test(owned))throw new Error('Generator browser requires the parent-owned disposable SQL fixture.');
async function login(page:Page){await page.goto('/gen');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('admin123');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('heading',{name:'代码生成',exact:true})).toBeVisible();}
async function headers(page:Page){return {Authorization:'Bearer '+await page.evaluate(()=>JSON.parse(sessionStorage.getItem('eforge.enterprise.session.v1')!).accessToken as string)};}
function files(buffer:Buffer){
  const end=buffer.lastIndexOf(Buffer.from([80,75,5,6]));if(end<0)throw new Error('Not a ZIP');let cursor=buffer.readUInt32LE(end+16);const result=new Map<string,string>();
  for(let i=0;i<buffer.readUInt16LE(end+10);i++){expect(buffer.readUInt32LE(cursor)).toBe(0x02014b50);const method=buffer.readUInt16LE(cursor+10),length=buffer.readUInt32LE(cursor+20),n=buffer.readUInt16LE(cursor+28),extra=buffer.readUInt16LE(cursor+30),comment=buffer.readUInt16LE(cursor+32),offset=buffer.readUInt32LE(cursor+42),name=buffer.subarray(cursor+46,cursor+46+n).toString('utf8');const start=offset+30+buffer.readUInt16LE(offset+26)+buffer.readUInt16LE(offset+28),bytes=buffer.subarray(start,start+length);result.set(name,(method===8?inflateRawSync(bytes):bytes).toString('utf8'));cursor+=46+n+extra+comment;}
  return result;
}
test('real generator import, exact config choices, sync, inert preview, identical ZIP and configured output preserve owned rows',async({page})=>{
  const errors:string[]=[];page.on('pageerror',cause=>errors.push(cause.message));await login(page);const auth=await headers(page);let id:string|undefined;
  try{
    await page.getByRole('button',{name:'导入表',exact:true}).click();const importing=page.getByRole('dialog');await importing.getByLabel('待导入表名称',{exact:true}).fill(owned!);await importing.getByRole('button',{name:'查找数据库表',exact:true}).click();await importing.getByRole('checkbox',{name:'选择待导入表 '+owned,exact:true}).check();await importing.getByRole('button',{name:'导入所选表',exact:true}).click();await expect(importing).toHaveCount(0);
    await page.getByLabel('表名称筛选',{exact:true}).fill(owned!);await page.getByRole('button',{name:'查询',exact:true}).click();await expect(page.getByRole('cell',{name:owned,exact:true})).toBeVisible();const listed=await page.request.get('/api/v1/tool/generator/tables?name='+owned,{headers:auth});expect(listed.status()).toBe(200);id=(await listed.json()).items[0].id;expect(typeof id).toBe('string');
    await page.getByRole('button',{name:'编辑 '+owned,exact:true}).click();const editor=page.getByRole('dialog');await editor.getByRole('tab',{name:'生成信息',exact:true}).click();await editor.getByLabel('前端类型',{exact:true}).selectOption('eforge-react');await editor.getByLabel('上级菜单',{exact:true}).selectOption({label:'系统工具'});await editor.getByLabel('生成功能名',{exact:true}).fill('<script>管理验证</script>');await editor.getByLabel('生成方式',{exact:true}).selectOption('1');await editor.getByLabel('自定义路径',{exact:true}).fill('/');await editor.getByRole('tab',{name:'字段信息',exact:true}).click();await editor.getByLabel('显示控件 status',{exact:true}).selectOption('select');await editor.getByLabel('字典类型 status',{exact:true}).selectOption('sys_common_status');await editor.getByRole('button',{name:'拖动排序 status',exact:true}).dragTo(editor.getByLabel('字段描述 entry_id',{exact:true}).locator('xpath=ancestor::tr'));await editor.getByRole('button',{name:'保存配置',exact:true}).click();await expect(editor).toHaveCount(0);
    const detailResponse=await page.request.get('/api/v1/tool/generator/tables/'+id,{headers:auth});expect(detailResponse.status()).toBe(200);const detail:TableDetail=await detailResponse.json();expect(detail.table.webType).toBe('eforge-react');expect(detail.configuration.options.parentMenuId).toBe('3');expect(detail.columns.find(field=>field.name==='status')?.dictionaryType).toBe('sys_common_status');expect(detail.columns[0]?.name).toBe('status');const fieldIds=detail.columns.map(field=>field.id);
    await page.getByRole('button',{name:'同步 '+owned,exact:true}).click();await page.getByRole('button',{name:'确认操作',exact:true}).click();await expect(page.getByRole('alertdialog')).toHaveCount(0);const synced:TableDetail=await (await page.request.get('/api/v1/tool/generator/tables/'+id,{headers:auth})).json();expect(synced.columns.map(field=>field.id).sort()).toEqual([...fieldIds].sort());expect(synced.columns.map(field=>field.name)).toEqual(['entry_id','name','status']);
    await page.getByRole('button',{name:'预览 '+owned,exact:true}).click();const previewDialog=page.getByRole('dialog');await expect(previewDialog.getByLabel('预览文件')).toBeVisible();await expect(previewDialog.locator('script,img')).toHaveCount(0);const previewResponse=await page.request.get('/api/v1/tool/generator/tables/'+id+'/preview',{headers:auth});expect(previewResponse.status()).toBe(200);const preview:PreviewResponse=await previewResponse.json();expect(preview.files?.some(file=>file.path?.endsWith('Page.tsx'))).toBe(true);await previewDialog.getByRole('button',{name:'关闭预览'}).click();
    const pending=page.waitForEvent('download');await page.getByRole('button',{name:'下载 '+owned,exact:true}).click();const archive=await pending;const content=files(await readFile((await archive.path())!));expect(content.size).toBe(preview.files!.length);for(const file of preview.files!){expect(typeof file.path).toBe('string');expect(content.get(file.path!)).toBe(file.content);}
    await page.getByRole('button',{name:'生成代码 '+owned,exact:true}).click();await page.getByRole('button',{name:'确认操作',exact:true}).click();if(process.env.EFORGE_E2E_CUSTOM_OUTPUT==='true'){await expect(page.getByRole('alertdialog')).toHaveCount(0);await expect(page.getByLabel('自定义输出结果')).toContainText('已创建');}else{await expect(page.getByRole('alertdialog').getByRole('alert')).toContainText('未启用');await page.getByRole('button',{name:'取消',exact:true}).click();}
    await page.setViewportSize({width:375,height:812});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.getByRole('button',{name:'删除 '+owned,exact:true}).click();await page.getByRole('button',{name:'确认操作',exact:true}).click();await expect(page.getByRole('alertdialog')).toHaveCount(0);expect((await page.request.get('/api/v1/tool/generator/tables/'+id,{headers:auth})).status()).toBe(404);expect(errors).toEqual([]);id=undefined;
  }finally{if(id)expect((await page.request.delete('/api/v1/tool/generator/tables',{headers:auth,data:{ids:[id]}})).status()).toBe(204);}
});
test('real admin creation reports retained partial DDL without automatically retrying',async({page})=>{
  await login(page);await page.getByRole('button',{name:'创建表',exact:true}).click();const dialog=page.getByRole('dialog'),prefix=owned+'_partial';
  await dialog.getByLabel('建表 SQL',{exact:true}).fill('CREATE TABLE '+prefix+'_first(id INT); CREATE TABLE '+prefix+'_bad(value VARCHAR(70000)); CREATE TABLE '+prefix+'_last(id INT)');
  const response=page.waitForResponse(response=>response.url().endsWith('/api/v1/tool/generator/creations')&&response.request().method()==='POST');await dialog.getByRole('button',{name:'执行建表',exact:true}).click();expect((await response).status()).toBe(500);await expect(dialog.getByLabel('建表结果')).toContainText(prefix+'_first：已创建');await expect(dialog).toContainText(prefix+'_bad：失败');await expect(dialog).toContainText(prefix+'_last：未尝试');
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'创建表',exact:true}).click();await dialog.getByLabel('建表 SQL',{exact:true}).fill('CREATE TABLE IF NOT EXISTS '+prefix+'_first(id INT)');const conflict=page.waitForResponse(response=>response.url().endsWith('/api/v1/tool/generator/creations'));await dialog.getByRole('button',{name:'执行建表',exact:true}).click();expect((await conflict).status()).toBe(409);await expect(dialog.getByRole('alert')).toBeVisible();await dialog.getByRole('button',{name:'关闭',exact:true}).click();
});
test('real generator list-only role hides mutations and revocation denies the route and all writes',async({page})=>{
  await login(page);const admin=await headers(page),suffix=Date.now().toString(),username='gm'+suffix;
  const createdRole=await page.request.post('/api/v1/system/roles',{headers:admin,data:{name:'Generator '+suffix,key:'generator-'+suffix,sort:9,status:'0',remark:'',menuLinked:false,menuKeys:['tool','tool-generator']}});expect(createdRole.status()).toBe(201);const role=await createdRole.json();let account:{id:string}|undefined;
  try{
    const created=await page.request.post('/api/v1/system/users',{headers:admin,data:{user:{username,displayName:'生成只读',departmentId:'103',email:'',phone:'',sex:'2',status:'0',roleIds:[],postIds:[]},password:'User12345'}});expect(created.status()).toBe(201);account=await created.json();expect((await page.request.put('/api/v1/system/users/'+account!.id+'/roles',{headers:admin,data:{roleIds:[role.id]}})).status()).toBe(204);
    const signed=await page.request.post('/api/v1/auth/login',{data:{username,password:'User12345'}});expect(signed.status()).toBe(200);const ownToken=(await signed.json()).accessToken,ownHeaders={Authorization:'Bearer '+ownToken};await page.evaluate(accessToken=>sessionStorage.setItem('eforge.enterprise.session.v1',JSON.stringify({accessToken})),ownToken);await page.reload();await expect(page.getByRole('heading',{name:'代码生成',exact:true})).toBeVisible();for(const name of ['导入表','创建表','编辑所选','删除所选','下载所选'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
    expect((await page.request.post('/api/v1/tool/generator/creations',{headers:ownHeaders,data:{sql:'CREATE TABLE '+owned+'_denied(id INT)'}})).status()).toBe(403);expect((await page.request.post('/api/v1/tool/generator/imports',{headers:ownHeaders,data:{names:[owned]}})).status()).toBe(403);expect((await page.request.delete('/api/v1/tool/generator/tables',{headers:ownHeaders,data:{ids:['1']}})).status()).toBe(403);expect((await page.request.get('/api/v1/tool/generator/tables/1',{headers:ownHeaders})).status()).toBe(403);
    expect((await page.request.put('/api/v1/system/users/'+account!.id+'/roles',{headers:admin,data:{roleIds:[]}})).status()).toBe(204);await page.reload();await expect(page.getByRole('heading',{name:'暂无访问权限'})).toBeVisible();const options=await page.request.get('/api/v1/tool/generator/menu-options',{headers:ownHeaders});expect(options.status()).toBe(200);expect(await options.json()).toEqual([]);expect((await page.request.get('/api/v1/tool/generator/tables',{headers:ownHeaders})).status()).toBe(403);
  }finally{if(account)expect((await page.request.delete('/api/v1/system/users',{headers:admin,data:{ids:[account.id]}})).status()).toBe(204);expect((await page.request.delete('/api/v1/system/roles',{headers:admin,data:{ids:[role.id]}})).status()).toBe(204);}
});
test('real manager creates a batch and saves tree then subtable relations with actual rendered files',async({page})=>{
  await login(page);const auth=await headers(page),root=owned+'_schema_root',child=owned+'_schema_child';let ids:string[]=[];
  try{
    await page.getByRole('button',{name:'创建表',exact:true}).click();const creating=page.getByRole('dialog');await creating.getByLabel('建表 SQL',{exact:true}).fill('CREATE TABLE '+root+" (entry_id BIGINT PRIMARY KEY AUTO_INCREMENT,parent_id BIGINT NOT NULL DEFAULT 0,name VARCHAR(64)) COMMENT='树主表'; CREATE TABLE "+child+" (child_id BIGINT PRIMARY KEY AUTO_INCREMENT,root_id BIGINT NOT NULL,name VARCHAR(64)) COMMENT='关联子表'");await creating.getByRole('button',{name:'执行建表',exact:true}).click();await expect(creating.getByLabel('建表结果')).toContainText('配置导入：已导入');await creating.getByRole('button',{name:'关闭',exact:true}).click();
    const listed=await page.request.get('/api/v1/tool/generator/tables?name='+owned+'_schema',{headers:auth});expect(listed.status()).toBe(200);const tables=(await listed.json()).items;ids=tables.map((table:{id:string})=>table.id);expect(ids).toHaveLength(2);const rootId=tables.find((table:{name:string})=>table.name===root).id;
    await page.getByLabel('表名称筛选',{exact:true}).fill(root);await page.getByRole('button',{name:'查询',exact:true}).click();await page.getByRole('button',{name:'编辑 '+root,exact:true}).click();const editor=page.getByRole('dialog');await editor.getByRole('tab',{name:'生成信息',exact:true}).click();await editor.getByLabel('生成模板',{exact:true}).selectOption('tree');await editor.getByLabel('树编码字段',{exact:true}).selectOption('entry_id');await editor.getByLabel('树父编码字段',{exact:true}).selectOption('parent_id');await editor.getByLabel('树名称字段',{exact:true}).selectOption('name');await editor.getByRole('button',{name:'保存配置',exact:true}).click();await expect(editor).toHaveCount(0);
    const tree:TableDetail=await (await page.request.get('/api/v1/tool/generator/tables/'+rootId,{headers:auth})).json();expect(tree.table.category).toBe('tree');expect(tree.configuration.options).toMatchObject({treeCode:'entry_id',treeParentCode:'parent_id',treeName:'name'});const treePreview=await page.request.get('/api/v1/tool/generator/tables/'+rootId+'/preview',{headers:auth});expect(treePreview.status()).toBe(200);const treeFiles:PreviewResponse=await treePreview.json();expect(treeFiles.files?.some(file=>file.content?.includes('extends TreeEntity'))).toBe(true);
    await page.getByRole('button',{name:'编辑 '+root,exact:true}).click();await editor.getByRole('tab',{name:'生成信息',exact:true}).click();await editor.getByLabel('生成模板',{exact:true}).selectOption('sub');await editor.getByLabel('关联子表',{exact:true}).selectOption(child);await editor.getByLabel('子表外键',{exact:true}).selectOption('root_id');await editor.getByRole('button',{name:'保存配置',exact:true}).click();await expect(editor).toHaveCount(0);const sub:TableDetail=await (await page.request.get('/api/v1/tool/generator/tables/'+rootId,{headers:auth})).json();expect(sub.table.category).toBe('sub');expect(sub.configuration).toMatchObject({subTableName:child,subTableForeignKey:'root_id'});const subPreview=await page.request.get('/api/v1/tool/generator/tables/'+rootId+'/preview',{headers:auth});expect(subPreview.status()).toBe(200);const subFiles:PreviewResponse=await subPreview.json();expect(subFiles.files?.some(file=>file.path?.includes('SchemaChild.java'))).toBe(true);
  }finally{if(ids.length)expect((await page.request.delete('/api/v1/tool/generator/tables',{headers:auth,data:{ids}})).status()).toBe(204);}
});
