import type {MenuResponse,MenuWriteRequest,NavigationNode} from '../../generated/api';
import {test,expect} from '@playwright/test';
test('real bootstrap navigation search and internal breadcrumb preserve authorization and logout',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/dashboard');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('admin123');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('heading',{name:/^你好，/})).toBeVisible();
  const nav=page.locator('.ef-app-shell__nav'),system=nav.getByRole('button',{name:'系统管理',exact:true}),monitor=nav.getByRole('button',{name:'系统监控',exact:true});
  await expect(system).toHaveAttribute('aria-expanded','false');await system.focus();await system.press('Enter');await expect(system).toHaveAttribute('aria-expanded','true');
  await monitor.click();await expect(system).toHaveAttribute('aria-expanded','false');await expect(monitor).toHaveAttribute('aria-expanded','true');await expect(page).toHaveURL(/\/dashboard$/);
  await expect(nav.getByRole('link',{name:'系统管理',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'导航搜索',exact:true}).click();const dialog=page.getByRole('dialog',{name:'导航搜索'}),input=dialog.getByRole('combobox',{name:'菜单搜索'});await expect(input).toBeFocused();await input.fill('/role');
  await expect(dialog.getByRole('option')).toHaveCount(1);await input.press('ArrowDown');await input.press('Enter');await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();
  await page.goto('/role/users/2');await expect(page.getByRole('heading',{name:'用户授权',exact:true})).toBeVisible();const crumbs=page.getByRole('navigation',{name:'面包屑'});await expect(crumbs.getByRole('link',{name:'面包屑：角色管理'})).toHaveAttribute('href','/role');await expect(crumbs).toContainText('用户授权');await crumbs.getByRole('link',{name:'面包屑：角色管理'}).click();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();
  const sidebar=page.locator('.ef-app-shell__sidebar');await page.getByLabel('角色名称筛选',{exact:true}).fill('侧栏真实草稿');
  await page.getByRole('button',{name:'收起菜单',exact:true}).click();await expect.poll(async()=>Math.round((await sidebar.boundingBox())!.width)).toBe(54);
  await system.hover();await expect(nav.getByRole('link',{name:'角色管理',exact:true})).toBeVisible();await system.focus();await system.press('Escape');await expect(system).toBeFocused();await expect(nav.getByRole('link',{name:'角色管理',exact:true})).toBeHidden();
  await page.getByRole('button',{name:'展开菜单',exact:true}).click();await expect(page.getByLabel('角色名称筛选',{exact:true})).toHaveValue('侧栏真实草稿');await expect.poll(async()=>Math.round((await sidebar.boundingBox())!.width)).toBe(200);
  await page.getByRole('button',{name:'收起菜单',exact:true}).click();await page.reload();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();await expect.poll(async()=>Math.round((await sidebar.boundingBox())!.width)).toBe(54);
  await system.focus();await system.press('Enter');await nav.getByRole('link',{name:'用户管理',exact:true}).click();await expect(page.getByRole('heading',{name:'用户管理',exact:true})).toBeVisible();await expect(nav.getByRole('link',{name:'角色管理',exact:true})).toBeHidden();
  await page.getByRole('button',{name:'展开菜单',exact:true}).click();await nav.getByRole('link',{name:'角色管理',exact:true}).click();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'布局设置',exact:true}).click();const layout=page.getByRole('dialog',{name:'布局设置',exact:true});await layout.getByLabel('混合菜单',{exact:true}).check();await layout.getByRole('button',{name:'保存配置',exact:true}).click();await layout.getByRole('button',{name:'关闭设置',exact:true}).click();
  const top=page.getByRole('navigation',{name:'顶部菜单',exact:true});await expect(nav.getByRole('button',{name:'系统管理',exact:true})).toHaveCount(0);await expect(nav.getByRole('link',{name:'角色管理',exact:true})).toBeVisible();
  await page.getByLabel('角色名称筛选',{exact:true}).fill('混合真实草稿');await top.getByRole('button',{name:'系统监控',exact:true}).click();await expect(nav.getByRole('link',{name:'在线用户',exact:true})).toBeVisible();await expect(page.getByLabel('角色名称筛选',{exact:true})).toHaveValue('混合真实草稿');await expect(page).toHaveURL(/\/role$/);
  await top.getByRole('button',{name:'系统管理',exact:true}).click();await nav.getByRole('link',{name:'角色管理',exact:true}).click();await page.reload();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();await expect(top.getByRole('button',{name:'系统管理',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'布局设置',exact:true}).click();await layout.getByLabel('顶部菜单',{exact:true}).check();await layout.getByRole('button',{name:'保存配置',exact:true}).click();await layout.getByRole('button',{name:'关闭设置',exact:true}).click();await expect(sidebar).toBeHidden();
  await top.getByRole('button',{name:'系统管理',exact:true}).click();await top.getByRole('link',{name:'用户管理',exact:true}).click();await expect(page.getByRole('heading',{name:'用户管理',exact:true})).toBeVisible();await expect(sidebar).toBeHidden();
  await page.getByRole('button',{name:'布局设置',exact:true}).click();await layout.getByRole('button',{name:'恢复默认',exact:true}).click();await layout.getByRole('button',{name:'关闭设置',exact:true}).click();await expect(top).toHaveCount(0);await nav.getByRole('link',{name:'角色管理',exact:true}).click();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();
  await page.getByLabel('角色名称筛选',{exact:true}).fill('主题真实草稿');
  await page.getByRole('button',{name:'布局设置',exact:true}).click();
  await layout.getByLabel('侧栏风格',{exact:true}).selectOption('light');await layout.getByLabel('主题颜色',{exact:true}).fill('#883399');await layout.getByLabel('界面尺寸',{exact:true}).selectOption('mini');await layout.getByLabel('动态标题',{exact:true}).check();await layout.getByLabel('显示页面标签',{exact:true}).uncheck();await layout.getByLabel('显示 Logo',{exact:true}).uncheck();await layout.getByLabel('显示页脚',{exact:true}).check();await layout.getByLabel('页脚内容',{exact:true}).fill('<img src=x onerror=alert(1)> 真实页脚');await layout.getByRole('button',{name:'保存配置',exact:true}).click();await layout.getByRole('button',{name:'关闭设置',exact:true}).click();
  await expect(sidebar).toHaveCSS('background-color','rgb(255, 255, 255)');await expect(page.getByLabel('角色名称筛选',{exact:true})).toHaveCSS('font-size','12px');await expect(page.getByLabel('角色名称筛选',{exact:true})).toHaveValue('主题真实草稿');await expect(page).toHaveTitle('角色管理 - EForge Enterprise');await expect(page.locator('.enterprise-footer')).toHaveText('<img src=x onerror=alert(1)> 真实页脚');await expect(page.locator('img[src="x"]')).toHaveCount(0);
  await page.reload();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();await expect(page.getByLabel('角色名称筛选',{exact:true})).toHaveCSS('font-size','12px');await page.getByRole('button',{name:'进入屏幕全屏',exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement!==null)).toBe(true);await page.getByRole('button',{name:'退出屏幕全屏',exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement===null)).toBe(true);
  await page.getByRole('button',{name:'布局设置',exact:true}).click();await layout.getByRole('button',{name:'恢复默认',exact:true}).click();await layout.getByRole('button',{name:'关闭设置',exact:true}).click();await expect(page.locator('.enterprise-footer')).toHaveCount(0);await expect(page).toHaveTitle('EForge Enterprise');
  await page.setViewportSize({width:991,height:844});const opener=page.getByRole('button',{name:'打开菜单',exact:true});
  await expect(page.locator('.ef-app-shell__sidebar')).toBeHidden();await opener.click();const menu=page.getByRole('dialog',{name:'菜单',exact:true});
  await expect(menu).toBeVisible();await expect(page.locator('body')).toHaveCSS('overflow','hidden');await expect(menu.getByRole('button',{name:'系统管理',exact:true})).toHaveAttribute('aria-expanded','true');
  await menu.getByRole('button',{name:'关闭菜单',exact:true}).focus();await page.keyboard.press('Shift+Tab');expect(await menu.evaluate(element=>element.contains(document.activeElement))).toBe(true);
  await page.keyboard.press('Escape');await expect(menu).toHaveCount(0);await expect(opener).toBeFocused();await expect(page.locator('body')).toHaveCSS('overflow','visible');
  await opener.click();await menu.getByRole('link',{name:'工作台',exact:true}).click();await expect(page.getByRole('heading',{name:/^你好，/})).toBeVisible();await expect(menu).toHaveCount(0);
  await opener.click();await menu.getByRole('button',{name:'系统管理',exact:true}).click();await menu.getByRole('link',{name:'角色管理',exact:true}).click();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();await expect(menu).toHaveCount(0);
  await opener.click();await page.mouse.click(980,700);await expect(menu).toHaveCount(0);await expect(opener).toBeFocused();await opener.click();
  await page.setViewportSize({width:992,height:844});await expect(menu).toHaveCount(0);await expect(page.locator('.ef-app-shell__sidebar')).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'导航搜索',exact:true}).click();await input.fill('no-such-page');await expect(dialog.getByRole('option')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await input.press('Escape');await expect(page.getByRole('button',{name:'导航搜索',exact:true})).toBeFocused();await page.getByRole('button',{name:'导航搜索',exact:true}).click();await expect(dialog).toBeVisible();await page.mouse.click(5,5);await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'导航搜索',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'退出登录'}).click();await expect(page.getByRole('heading',{name:'登录工作空间'})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);expect(errors).toEqual([]);
});
test('real SQL menu defaults preserve exact query links, active state, search and internal parent breadcrumbs',async({page})=>{
  await page.goto('/dashboard');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('admin123');
  await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('heading',{name:/^你好，/})).toBeVisible();
  const token=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('eforge.enterprise.session.v1')!).accessToken as string);
  const auth={Authorization:'Bearer '+token};
  const listResponse=await page.request.get('/api/v1/system/menus',{headers:auth});expect(listResponse.status()).toBe(200);
  const menus=await listResponse.json() as MenuResponse[],menu=menus.find(row=>row.key==='system-roles')!;
  expect(menu).toBeTruthy();
  const original:MenuWriteRequest={key:menu.key!,name:menu.name,parentId:menu.parentId,sort:menu.sort,type:menu.type,status:menu.status,visible:menu.visible,
    routeId:menu.routeId,externalUrl:menu.externalUrl,permission:menu.permission,icon:menu.icon,remark:menu.remark,groupPath:menu.groupPath,queryText:menu.queryText,cached:menu.cached};
  const queryText='{"id":"9007199254740999","__proto__":"文字 &?/#","list":["a","b"],"bare":null}';
  const href='/role?id=9007199254740999&__proto__=%E6%96%87%E5%AD%97%20%26%3F%2F%23&list=a&list=b&bare';
  function find(nodes:NavigationNode[]):NavigationNode|undefined {for(const node of nodes){if(node.key==='system-roles')return node;const child=find(node.children);if(child)return child;}}
  try{
    expect((await page.request.put('/api/v1/system/menus/'+menu.id,{headers:auth,data:{...original,queryText,cached:false}})).status()).toBe(204);
    const bootstrap=await page.request.get('/api/v1/app/bootstrap',{headers:auth});expect(bootstrap.status()).toBe(200);
    expect(find((await bootstrap.json()).navigation)).toMatchObject({queryText,cached:false,type:'ROUTE'});
    await page.reload();await expect(page.getByRole('heading',{name:/^你好，/})).toBeVisible();
    const link=page.locator('.ef-app-shell__nav').getByRole('link',{name:'角色管理',exact:true});
    await page.locator('.ef-app-shell__nav').getByRole('button',{name:'系统管理',exact:true}).click();await expect(link).toHaveAttribute('href',href);await link.click();await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();
    expect(new URL(page.url()).search).toBe(href.slice('/role'.length));await expect(link).toHaveAttribute('aria-current','page');
    await page.goto('/role/users/2');await expect(page.getByRole('heading',{name:'用户授权',exact:true})).toBeVisible();
    await expect(page.getByRole('navigation',{name:'面包屑'}).getByRole('link',{name:'面包屑：角色管理'})).toHaveAttribute('href',href);
    await page.getByRole('button',{name:'导航搜索',exact:true}).click();const input=page.getByRole('dialog',{name:'导航搜索'}).getByRole('combobox',{name:'菜单搜索'});
    await input.fill('角色管理');await expect(page.getByRole('dialog',{name:'导航搜索'}).getByRole('option')).toHaveCount(1);await input.press('ArrowDown');await input.press('Enter');
    await expect(page.getByRole('heading',{name:'角色管理',exact:true})).toBeVisible();expect(new URL(page.url()).search).toBe(href.slice('/role'.length));
  }finally{expect((await page.request.put('/api/v1/system/menus/'+menu.id,{headers:auth,data:original})).status()).toBe(204);}
  await page.getByRole('button',{name:'退出登录'}).click();await expect(page.getByRole('heading',{name:'登录工作空间'})).toBeVisible();
});
