import {test,expect} from '@playwright/test';
test('actual login and revocation keep explicitly remembered credentials separate from the Redis session',async({page})=>{
  let logins=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/api/v1/auth/login' && request.method()==='POST')logins++;});
  await page.goto('/login');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('admin123');const remember=page.getByRole('checkbox',{name:'在此浏览器记住密码（30天）'});await remember.check();await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.locator('.account-name')).toBeVisible();expect(logins).toBe(1);
  const token=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('eforge.enterprise.session.v1') ?? '{}').accessToken as string);expect(token).toBeTruthy();
  await page.getByRole('button',{name:'退出登录',exact:true}).click();await expect(page.getByRole('heading',{name:'登录工作空间'})).toBeVisible();await expect(page.getByLabel('账号',{exact:true})).toHaveValue('admin');await expect(page.getByLabel('密码',{exact:true})).toHaveValue('admin123');await expect(remember).toBeChecked();expect(logins).toBe(1);
  const invalidated=await page.request.get(`${process.env.EFORGE_E2E_BACKEND_URL}/api/v1/app/bootstrap`,{headers:{Authorization:`Bearer ${token}`}});expect(invalidated.status()).toBe(401);expect(await page.evaluate(()=>sessionStorage.getItem('eforge.enterprise.session.v1'))).toBeNull();
  await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.locator('.account-name')).toBeVisible();expect(logins).toBe(2);await page.getByRole('button',{name:'退出登录',exact:true}).click();await expect(remember).toBeChecked();await remember.uncheck();await expect(page.getByRole('status').filter({hasText:'已清除本浏览器记住的密码。'})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'登录',exact:true})).toBeEnabled();await expect(page.getByLabel('账号',{exact:true})).toHaveValue('');await expect(page.getByLabel('密码',{exact:true})).toHaveValue('');expect(logins).toBe(2);
});
