import {test,expect} from '@playwright/test';
test('actual current-user unlock restores a retained profile, survives refresh, and logout revokes the old session',async({page})=>{
  await page.goto('/user/profile');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('admin123');await page.getByRole('button',{name:'登录',exact:true}).click();
  const nickname=page.getByLabel('用户昵称',{exact:true});await expect(nickname).toBeVisible();await nickname.fill('锁屏前未保存昵称');const token=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('eforge.enterprise.session.v1')??'{}').accessToken as string);expect(token).toBeTruthy();
  await page.getByRole('button',{name:'锁定屏幕',exact:true}).click();await expect(page.getByLabel('解锁密码')).toBeVisible();await expect(nickname).not.toBeVisible();await page.getByLabel('解锁密码').fill('Wrong123');await page.getByLabel('解锁密码').press('Enter');await expect(page.getByRole('alert')).toHaveText('密码不正确，请重新输入。');await expect(page.getByLabel('解锁密码')).toHaveValue('');await expect(page.getByLabel('解锁密码')).toBeFocused();
  await page.getByLabel('解锁密码').fill('admin123');await page.getByLabel('解锁密码').press('Enter');await expect(nickname).toBeVisible();await expect(nickname).toHaveValue('锁屏前未保存昵称');await expect(page).toHaveURL(/\/user\/profile$/);expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('eforge.enterprise.session.v1')??'{}').accessToken)).toBe(token);
  await page.getByRole('button',{name:'锁定屏幕',exact:true}).click();await page.reload();await expect(page.getByLabel('解锁密码')).toBeVisible();await page.goto('/user/profile');await expect(page.getByLabel('解锁密码')).toBeVisible();await expect(nickname).not.toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.getByLabel('解锁密码').fill('admin123');await page.getByRole('button',{name:'解锁',exact:true}).click();await expect(nickname).toBeVisible();await expect(nickname).not.toHaveValue('锁屏前未保存昵称');
  await page.getByRole('button',{name:'锁定屏幕',exact:true}).click();await page.getByRole('button',{name:'退出重新登录',exact:true}).click();await expect(page.getByRole('heading',{name:'登录工作空间'})).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem('eforge.enterprise.screen-lock.v1'))).toBeNull();const expired=await page.request.post(`${process.env.EFORGE_E2E_BACKEND_URL}/api/v1/auth/unlock-screen`,{headers:{Authorization:`Bearer ${token}`},data:{password:'admin123'}});expect(expired.status()).toBe(401);
});
