import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import {createBrowserRouterAdapter} from '@eforge/app';
import {EForgeProvider} from '../ui/controls';
import '../ui/theme.css';
import {Application} from './Application';
import {browserSessionStorage, createSessionRuntime} from '../integration/session';
const runtime = createSessionRuntime(browserSessionStorage());
const router = createBrowserRouterAdapter();
void runtime.restore();
const root = document.getElementById('root');
if (!root) throw new Error('Missing application root.');
createRoot(root).render(<StrictMode><EForgeProvider><Application runtime={runtime} router={router} /></EForgeProvider></StrictMode>);
