import {test, expect} from './fixtures';
import type {Page} from '@playwright/test';
async function login(page: Page, permission = 'monitor:job:query') {
  await page.route('**/captchaImage', route => route.fulfill({json: {code: 200, captchaEnabled: false}}));
  await page.route('**/api/v1/auth/login', route => route.fulfill({json: {accessToken: 'cron-token', tokenType: 'Bearer'}}));
  await page.route('**/api/v1/app/bootstrap', route => route.fulfill({json: {user: {id: '2', username: 'reader', displayName: '账号'}, roles: [], permissions: ['monitor:job:list', permission], navigation: [{key: 'monitor', type: 'GROUP', label: '系统监控', order: 0, children: [{key: 'monitor-jobs', type: 'ROUTE', routeId: 'monitor-jobs', label: '定时任务', order: 1, children: []}]}]}}));
  await page.route('**/api/v1/monitor/jobs?*', route => route.fulfill({json: {items: [{id: '1', name: '任务', cronExpression: '0 0 0 L * ?'}], total: 1, page: 1, pageSize: 10}}));
  await page.route('**/api/v1/monitor/jobs/1', route => route.fulfill({json: {id: '1', name: '任务', cronExpression: '0 0 0 L * ?'}}));
  await page.goto('/job'); await page.getByLabel('账号', {exact: true}).fill('reader'); await page.getByLabel('密码', {exact: true}).fill('password'); await page.getByRole('button', {name: '登录', exact: true}).click();
}
test('seven Cron fields retain range/interval/selection/date modes, raw refill, reset and detail handoff', async ({page}) => {
  await page.route('**/api/v1/monitor/jobs/cron-preview?*', route => route.fulfill({json: {zone: 'Asia/Shanghai', times: ['2099-01-01T00:00:00Z']}}));
  await login(page); await page.getByRole('button', {name: 'Cron表达式编辑', exact: true}).click(); const dialog = page.getByRole('dialog'), expression = dialog.getByLabel('Cron表达式', {exact: true});
  for (const [field, expected] of [['秒', '0/5 * * * * ?'], ['分钟', '0/5 0/5 * * * ?'], ['小时', '0/5 0/5 0/5 * * ?'], ['月', '0/5 0/5 0/5 * 1/5 ?'], ['年', '0/5 0/5 0/5 * 1/5 ? 1970/5']] as const) {
    await dialog.getByRole('tab', {name: field, exact: true}).click(); await dialog.getByLabel(`${field}模式`, {exact: true}).selectOption('step'); await dialog.getByLabel(`${field}间隔值`, {exact: true}).fill('5'); await expect(expression).toHaveValue(expected);
  }
  await dialog.getByRole('tab', {name: '小时', exact: true}).click(); await dialog.getByLabel('小时模式', {exact: true}).selectOption('range'); await dialog.getByLabel('小时开始值').fill('8'); await dialog.getByLabel('小时结束值').fill('18'); await expect(expression).toHaveValue('0/5 0/5 8-18 * 1/5 ? 1970/5');
  await dialog.getByRole('tab', {name: '秒', exact: true}).click(); await dialog.getByLabel('秒模式', {exact: true}).selectOption('list'); await dialog.getByRole('checkbox', {name: '秒取值 59', exact: true}).check(); await expect(expression).toHaveValue('0,59 0/5 8-18 * 1/5 ? 1970/5');
  await dialog.getByRole('tab', {name: '日', exact: true}).click(); await dialog.getByLabel('日模式', {exact: true}).selectOption('nearest'); await dialog.getByLabel('日日期').fill('15'); await expect(expression).toHaveValue('0,59 0/5 8-18 15W 1/5 ? 1970/5');
  await dialog.getByRole('tab', {name: '周', exact: true}).click(); await dialog.getByLabel('周模式', {exact: true}).selectOption('nth'); await dialog.getByLabel('周星期').fill('6'); await dialog.getByLabel('周序号').fill('5'); await expect(expression).toHaveValue('0,59 0/5 8-18 ? 1/5 6#5 1970/5');
  await dialog.getByLabel('周模式', {exact: true}).selectOption('weekdayLast'); await expect(expression).toHaveValue('0,59 0/5 8-18 ? 1/5 6L 1970/5');
  await expression.fill('0 0/5 8-18 ? JAN,MAR MON-FRI 2099'); await dialog.getByRole('button', {name: '回填字段'}).click(); await dialog.getByRole('tab', {name: '月', exact: true}).click(); await expect(dialog.getByLabel('月自定义字段')).toHaveValue('JAN,MAR');
  await expect(dialog.getByText('2099/01/01 08:00:00', {exact: true})).toBeVisible(); await dialog.getByRole('button', {name: '确认表达式'}).click(); await expect(page.getByLabel('已确认Cron表达式')).toHaveText('0 0/5 8-18 ? JAN,MAR MON-FRI 2099');
  await page.getByRole('button', {name: '详细任务 1'}).click(); await page.getByRole('button', {name: '编辑当前Cron表达式'}).click(); await expect(expression).toHaveValue('0 0 0 L * ?'); await dialog.getByRole('button', {name: '重置表达式'}).click(); await expect(expression).toHaveValue('* * * * * ?');
  await page.keyboard.press('Escape'); await expect(page.getByLabel('已确认Cron表达式')).toHaveText('0 0/5 8-18 ? JAN,MAR MON-FRI 2099'); await expect(page.getByRole('button', {name: '详细任务 1'})).toBeFocused();
});
test('preview failures and stale requests cannot confirm; exhausted expressions, keyboard/mobile and permission guards', async ({page}) => {
  let fail = true, resolveSlow: (() => void) | undefined; const slow = new Promise<void>(resolve => {resolveSlow = resolve;});
  await page.route('**/api/v1/monitor/jobs/cron-preview?*', async route => {const q = new URL(route.request().url()).searchParams.get('expression'); if (q === '0 0 0 1 1 ? 2099') await slow; await route.fulfill(fail ? {status: 503, json: {}} : q === 'invalid' ? {status: 400, json: {}} : {json: {zone: 'UTC', times: []}}).catch(() => {});});
  await login(page); await page.getByRole('button', {name: 'Cron表达式编辑', exact: true}).click(); const dialog = page.getByRole('dialog'), expression = dialog.getByLabel('Cron表达式', {exact: true}), confirm = dialog.getByRole('button', {name: '确认表达式'});
  await expect(dialog.getByRole('alert')).toContainText('服务暂时不可用'); await expect(confirm).toBeDisabled(); fail = false; await dialog.getByRole('button', {name: '重试预览'}).click(); await expect(confirm).toBeEnabled();
  const slowRequest = page.waitForRequest(request => request.url().includes('cron-preview') && new URL(request.url()).searchParams.get('expression') === '0 0 0 1 1 ? 2099'); await expression.fill('0 0 0 1 1 ? 2099'); await expect(confirm).toBeDisabled(); await slowRequest;
  await expression.fill('invalid'); await dialog.getByRole('button', {name: '回填字段'}).click(); await expect(dialog.getByRole('alert')).toContainText('六个字段'); resolveSlow!(); await expect(confirm).toBeDisabled();
  await expression.fill('0 0 0 1 1 ? 1970'); await dialog.getByRole('button', {name: '回填字段'}).click(); await expect(dialog.getByText('该有效表达式没有后续执行时间。')).toBeVisible(); await expect(confirm).toBeEnabled();
  await dialog.getByRole('tab', {name: '秒', exact: true}).focus(); await page.keyboard.press('End'); await expect(dialog.getByRole('tab', {name: '年', exact: true})).toBeFocused(); await expect(dialog.getByLabel('年模式')).toHaveValue('list'); await page.keyboard.press('ArrowRight'); await expect(dialog.getByRole('tab', {name: '秒', exact: true})).toBeFocused();
  await dialog.getByLabel('秒模式').selectOption('list'); await dialog.getByRole('checkbox', {name: '秒取值 0', exact: true}).uncheck(); await expect(dialog.getByRole('alert')).toContainText('至少指定'); await expect(confirm).toBeDisabled(); await dialog.getByRole('checkbox', {name: '秒取值 59', exact: true}).check();
  await page.setViewportSize({width: 375, height: 812}); expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true); await expect(confirm).toBeEnabled(); await confirm.click(); await expect(page.getByLabel('已确认Cron表达式')).toHaveText('59 0 0 1 1 ? 1970');
  await page.route('**/api/v1/app/bootstrap', route => route.fulfill({json: {user: {id: '2', username: 'reader', displayName: '账号'}, roles: [], permissions: ['monitor:job:list'], navigation: [{key: 'monitor', type: 'GROUP', label: '系统监控', order: 0, children: [{key: 'monitor-jobs', type: 'ROUTE', routeId: 'monitor-jobs', label: '定时任务', order: 1, children: []}]}]}})); await page.reload(); await expect(page.getByRole('heading', {name: '定时任务', exact: true})).toBeVisible(); await expect(page.getByRole('button', {name: 'Cron表达式编辑', exact: true})).toHaveCount(0);
});

test('remaining field modes and numeric guards preserve date exclusion and revalidate normalized input', async ({page}) => {
  let count = 0; await page.route('**/api/v1/monitor/jobs/cron-preview?*', route => {count++; return route.fulfill({json: {zone: 'UTC', times: []}});});
  await login(page); await page.getByRole('button', {name: 'Cron表达式编辑', exact: true}).click(); const dialog = page.getByRole('dialog'), expression = dialog.getByLabel('Cron表达式', {exact: true}), confirm = dialog.getByRole('button', {name: '确认表达式'});
  await expect(confirm).toBeEnabled(); const previous = count; await expression.fill('  *   * * * * ?  '); await expect.poll(() => count).toBeGreaterThan(previous); await expect(confirm).toBeEnabled();
  await expression.fill('0 0 0 1 1 ? 2099'); await dialog.getByRole('button', {name: '回填字段'}).click();
  await dialog.getByRole('tab', {name: '年', exact: true}).click(); await dialog.getByLabel('年模式').selectOption('range'); await dialog.getByLabel('年开始值').fill('2098'); await dialog.getByLabel('年结束值').fill('2099'); await expect(expression).toHaveValue('0 0 0 1 1 ? 2098-2099'); await dialog.getByLabel('年模式').selectOption('omit'); await expect(expression).toHaveValue('0 0 0 1 1 ?');
  await dialog.getByRole('tab', {name: '月', exact: true}).click(); await dialog.getByLabel('月模式').selectOption('list'); await dialog.getByRole('checkbox', {name: '月取值 12', exact: true}).check(); await expect(expression).toHaveValue('0 0 0 1 1,12 ?');
  await dialog.getByRole('tab', {name: '日', exact: true}).click(); await dialog.getByLabel('日模式').selectOption('last'); await expect(expression).toHaveValue('0 0 0 L 1,12 ?'); await dialog.getByLabel('日模式').selectOption('none'); await expect(expression).toHaveValue('0 0 0 ? 1,12 *');
  await dialog.getByRole('tab', {name: '周', exact: true}).click(); await dialog.getByLabel('周模式').selectOption('range'); await dialog.getByLabel('周开始值').fill('6'); await dialog.getByLabel('周结束值').fill('2'); await expect(expression).toHaveValue('0 0 0 ? 1,12 6-2'); await dialog.getByLabel('周模式').selectOption('list'); await dialog.getByRole('checkbox', {name: '周取值 2', exact: true}).check(); await expect(expression).toHaveValue('0 0 0 ? 1,12 1,2');
  await dialog.getByRole('tab', {name: '秒', exact: true}).click(); await dialog.getByLabel('秒模式').selectOption('range'); await dialog.getByLabel('秒结束值').fill('60'); await expect(dialog.getByRole('alert')).toContainText('0 到 59'); await expect(confirm).toBeDisabled(); await dialog.getByLabel('秒结束值').fill('59'); await expect(expression).toHaveValue('0-59 0 0 ? 1,12 1,2');
  await dialog.getByRole('tab', {name: '分钟', exact: true}).click(); await dialog.getByLabel('分钟模式').selectOption('step'); await dialog.getByLabel('分钟间隔值').fill('0'); await expect(dialog.getByRole('alert')).toContainText('1 到 60'); await expect(confirm).toBeDisabled(); await dialog.getByLabel('分钟间隔值').fill('15');
  await dialog.getByRole('tab', {name: '小时', exact: true}).click(); await dialog.getByLabel('小时模式').selectOption('list'); await dialog.getByRole('checkbox', {name: '小时取值 23', exact: true}).check(); await expect(expression).toHaveValue('0-59 0/15 0,23 ? 1,12 1,2'); await expect(confirm).toBeEnabled();
  await dialog.getByRole('button', {name: '取消', exact: true}).click(); await expect(page.getByLabel('已确认Cron表达式')).toHaveCount(0); await expect(page.getByRole('button', {name: 'Cron表达式编辑', exact: true})).toBeFocused();
});
