import {test,expect} from './fixtures';
async function openDashboard(page:import('@playwright/test').Page){
  await page.route('**/captchaImage',route=>route.fulfill({json:{code:200,captchaEnabled:false}}));await page.route('**/api/v1/auth/login',route=>route.fulfill({json:{accessToken:'dashboard-fixture',tokenType:'Bearer'}}));await page.route('**/api/v1/app/bootstrap',route=>route.fulfill({json:{user:{id:'1',username:'admin',displayName:'管理员'},roles:['admin'],permissions:['app:dashboard:view'],navigation:[{key:'dashboard',type:'ROUTE',routeId:'dashboard',label:'工作台',order:0,children:[]}]}}));
  await page.goto('/dashboard');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('Password123');await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('button',{name:'图表演示',exact:true}).click();await expect(page.getByRole('region',{name:'图表演示工作台'})).toBeVisible();
}

test('dashboard panels and chart cards appearance at desktop and phone widths',async({page},info)=>{
  await page.setViewportSize({width:1440,height:1000});await openDashboard(page);
  await page.getByRole('button',{name:'工作台',exact:true}).click();
  await page.screenshot({path:info.outputPath('workspace-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'图表演示',exact:true}).click();await expect(page.locator('.dashboard-demo-chart svg')).toHaveCount(4);
  await expect(page.getByRole('button',{name:/^订单：/}).locator('[aria-hidden=true]')).toHaveText('13,600');
  await page.screenshot({path:info.outputPath('charts-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:info.outputPath('charts-mobile.png'),fullPage:true});
});
test('original four metrics switch complete line data and preserve radar rose and stacked bar charts',async({page})=>{
  await openDashboard(page);await expect(page.locator('.dashboard-demo-chart svg')).toHaveCount(4);await expect(page.getByText('演示数据用于展示图表交互，不代表当前企业的实际业务统计。')).toBeVisible();
  const checkpoints=[['访客','100','120','165','145'],['消息','200','180','140','130'],['金额','80','120','100','130'],['订单','130','120','160','130']];
  for(const [metric,expected,actual,lastExpected,lastActual] of checkpoints){await page.getByRole('button',{name:new RegExp('^'+metric+'：')}).click();const summary=page.getByText('查看'+metric+'趋势数据',{exact:true});if(!await summary.evaluate(element=>(element.parentElement as HTMLDetailsElement).open))await summary.click();const table=page.getByRole('table',{name:metric+'趋势演示数据'});await expect(table.getByRole('row')).toHaveCount(8);await expect(table.getByRole('row').nth(1)).toHaveText('Mon'+expected+actual);await expect(table.getByRole('row').nth(7)).toHaveText('Sun'+lastExpected+lastActual);}
  await page.getByText('查看预算比较数据',{exact:true}).click();await expect(page.getByRole('table',{name:'预算比较演示数据'}).getByRole('row').nth(1)).toHaveText('Allocated Budget5000700012000110001500014000');await page.getByText('查看文章分布数据',{exact:true}).click();await expect(page.getByRole('table',{name:'文章分布演示数据'}).getByRole('row').nth(1)).toHaveText('Industries320');await page.getByText('查看页面访问数据',{exact:true}).click();await expect(page.getByRole('table',{name:'页面访问演示数据'}).getByRole('row').nth(1)).toHaveText('Mon798030');
  const legend=page.getByRole('group',{name:'订单趋势图例'}).getByRole('button',{name:'expected',exact:true});await legend.focus();await page.keyboard.press('Space');await expect(legend).toHaveAttribute('aria-pressed','false');await page.keyboard.press('Space');await expect(legend).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:/^订单：/}).locator('[aria-hidden=true]')).toHaveText('13,600');
  await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);for(const chart of await page.locator('.dashboard-demo-chart svg').all()){expect((await chart.boundingBox())?.width).toBeGreaterThan(100);}
  await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});await page.getByRole('button',{name:'工作台',exact:true}).click();await expect(page.getByRole('heading',{name:'你的工作空间已就绪'})).toBeVisible();await expect(page.locator('.dashboard-demo-chart')).toHaveCount(0);
});
test('chart initialization failure exposes complete data and retry recovers the actual renderer',async({page})=>{
  await openDashboard(page);await page.getByRole('button',{name:'工作台',exact:true}).click();await page.evaluate(()=>{const Original=ResizeObserver;Object.assign(window,{dashboardObserverFailed:true});Object.defineProperty(window,'ResizeObserver',{configurable:true,value:class extends Original{constructor(callback:ResizeObserverCallback){if((window as unknown as {dashboardObserverFailed:boolean}).dashboardObserverFailed)throw new Error('Fixture unavailable observer');super(callback);}}});});await page.getByRole('button',{name:'图表演示',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(4);await page.getByText('查看访客趋势数据',{exact:true}).click();await expect(page.getByRole('table',{name:'访客趋势演示数据'}).getByRole('row').nth(1)).toHaveText('Mon100120');await page.evaluate(()=>Object.assign(window,{dashboardObserverFailed:false}));for(const title of ['访客趋势','预算比较','文章分布','页面访问'])await page.getByRole('button',{name:'重试'+title+'图表'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('.dashboard-demo-chart svg')).toHaveCount(4);
});
